core.yml

Basic Auth

---

actions.yml

I have removed the user not found error example
I have added the invalid content example

Change payrequest 400 response examples

---

actions.yml

Changed the version to 1.0.1
Enhanced error object to match JSON specification here: https://jsonapi.org/format/#error-objects

Change version and error object

---

actions.yml

Changed the error object to have pointer instead of parameter

Changed Parameter to Pointer

---

core.yml

Updating getConsent EP, as raised by Jim..

Added type:consent instead of consentPolicy

---

actions.yml
core.yml
services.yml

Docs staging

---

core.yml
services.yml

Devx 176 docs class in accounts response schema is fixed

---

core.yml

Remove extra commas in jobs fields for payments

---

reports.yml

DEVX-279 Introducting Retrieve a report Endpoint

---

reports.yml

DEVX-282 Removed Links Object and cleaned the title

---

reports.yml

- Added Accounts and transactions Schema
- Removed Links

DX-285-report-docs-to-remove-links-and-add-schemas-for-accounts-&-transactions

---

affordability.yml

Refined and Removed an old default token from the Schemas.

DX-288-docs-refine-security-schema-for-affordability-ep

---

identity.yml

Changed Auth type to Bearer 
- Removed Oauth2 to Bearer

DX-293-reports-docs-fix-the-identity-ep-auth-schemas

---

.github/workflows/auto-approve.yml
.github/workflows/pr-lint.yml
LICENSE

Add auto approve dependabot action

DSO-1143 add auto approve dependabot action

---

.github/workflows/CI.yml
.github/workflows/pr-lint.yml

- Testing CI with auto tagging and releases.

DX-297-api-ref-add-auto-tagging-and-releases

---

.github/CODEOWNERS
core.yml

As Requested by Damir, to update these docs bugs.

DX-302 Update User First Middle and Last Names with Additional CodeOwner

---

reports.yml

DX-305 Report Endpoint updated with pagination to Transactions EP

---

.github/workflows/CI-pipeline.yml
.github/workflows/auto-approve.yml
.github/workflows/pr-lint.yml
.github/workflows/syncdev.yml

Update Github actions to use external github actions to point to commit sha apposed to release for security

DSO-1118 update github actions

---

enrich.yml
identity.yml

Auto complete stopped working and applied hot fix

DX-326  Update Security Schemas for Enrich and Identity

---

.github/workflows/CI-pipeline.yml
core.yml
payments.yml
services.yml

```
To update CI pipelines for Payments
To Remove Oauth2 to Bearer JWT API wide
Refactor Payments 
Refactor Core
Refactor Services
```

DX-328  Refactoring Oauth2 to Bearer JWT & Updating CI Payment pipelines

---

.github/workflows/syncdev.yml
draft-release/webhooks.yml

<details><summary>Details</summary>
<p>
Deploying on the draft mode and adding pipeline. 
</p>
</details>

DX-332 Webhooks pipeline draft mode

---

draft-release/webhooks.yml

```
To update Security schemes for Webhooks. 
```

DX-333 Updated Security schemes on draft mode

---

payments.yml

https://basiq.atlassian.net/browse/DX-336

Add more post examples without account details

---

.github/workflows/CI-pipeline.yml

DX-337 Updating DeployProd Pipeline for Payments

---

data.yml

DX-354 Transaction EP missing SubClass Object

---

reports.yml

DX-360 Size missing in Reports Transactions EP

---

data.yml

BASIQ Schema mapped with OB Schema for accounts MetaData Extensions Docs
- fees
- depositRates
- lendingRates
- loan
- creditCard

DX-346 accounts add docs for extending accounts ep with new cdr attributes

---

data.yml

DX-346 Removed Inconsistency

---

.github/workflows/CI-pipeline.yml

Removing Releases from Main Pipeline.

DX-334 CI-Pipeline Update to Remove Releases

---

draft-release/core.yml

DX-367 Updated Error details

---

data.yml

- Removed Go Lang extra attributes for OpenAPI Spec
- Fixed Typos

DX-372 Fixed Typos & removed Go extra attributes

---

reports.yml

- Updated accounts Link Schema in GET report/:id

DX-374 Add links to account object in GET /Reports/:id/ - Updated Links Schema

---

data.yml

DX-375 Replaced connectorCategory filter with connectorEngine in Connector EP 

---

core.yml

- This commit includes 401 in Core.

DX-373 Added 401 missing error schema

---

webhooks.yml

DX-382 Removed Nested Arrays in SubscribedEvents

---

enrich.yml

DX-385 Updated Enrich location response

---

data.yml

DX-388 Account Lending Rates application Frequency is formatted ISO-8601

---

webhooks.yml

[Urgent] Removed Secrets docs and aligned with Responses.

DX-389 Remove Secret from Webhooks

---

webhooks.yml

Secret exposing in Creating Webhooks and Updating Webhooks.

DX-391 Exposing Secrets in Webhooks POST

---

webhooks.yml

DX-391 Updated bad indentation of a mapping entry

---

core.yml

DX-394 Core API Spec Validation fix

---

.github/CODEOWNERS
reports.yml

Frequency update in Group and subgroups

DX-398 Conn Aff Report API group Frequency update

---

core.yml

Bug fixed from optional to conditional.

DX-397 AuthLinks update with Conditional Mobile Number

---

data.yml

Adding `accountsOwnerhship` Attribute to accounts EP

DX-403 Add `accountOwnership` attribute to Accounts EP

---

reports.yml

DX-426 Conn-aff Reports Renaming ME034 + ME039

---

webhooks.yml

Removing Beta Tags from Webhooks:

DX-431 Removing Beta release tags to Production Ready env

---

webhooks.yml

🧰 Changes
---
1. Fixed Minor Bugs. 
2. Removed Beta tags.

DX-431 Fixed Minor bug

---

core.yml

DX-250 Consent EP addition to docs for Expired JSON Example

---

reports.yml

DX-455 Addition of EXP-040+041, ME035

---

reports.yml

DX-465 ME001 renamed to `# OF IDENTIFIED SALARY SOURCES`

---

reports.yml

DX-464 rename ME004 to `OTHER POSSIBLE INCOME MONTHLY`

---

reports.yml

DX-466 Metrics rename ME018 to `% OF SALARY INCOME WITHDRAWN VIA ATM`

---

reports.yml

New Metrics addition for ME042.

DX-470 Conf-aff Add New Metrics of # of Recent Income sources ME042

---

data.yml

DX-474 Expose arrangement expiryDate in the Connections Endpoint

---

.github/workflows/CI-pipeline.yml

Added Prod Runners with Workflow Dispatch.

DX-479 Updating Prod runners for CI Pipeline

---

reports.yml

Adding Filters to GET /reports/types and GET /reports/types/{id}

DX-484 Add `required` Field for report filters

---

reports.yml

Adding EXP-058 on Retrieve Reports EP

DX-491 EXP058 Metrics Addition for Mortgage Transfers under Liabilities

---

data.yml

DX-492 Fixed BSB+AccountNo in Data

---

.github/CODEOWNERS

DX-503 Update KamBasiq to API Docs CodeOWNER

---

reports.yml

DX-502 Add new Metrics for ME048

---

reports.yml

New Metrics for Conf-aff ME047

DX-501 Add New Metrics for ME047

---

reports.yml

ME047 is Bool and will return true/false.

DX-501 Values switch to Bool

---

data.yml
enrich.yml

@kambasiq Fixed the suggested Edits as per here: https://github.com/basiqio/api-ref/pull/306

DX-485 Fixed suggested edits

---

core.yml

DX-504 Schema Fixed for Auth & Bearer

---

reports.yml

DX-528 Remove Beta-status tags from Conf-aff

---

payments.yml

DX-458 Support Collect Fast - with Payment agreements 

---

payments.yml

DX-457 Addition of Beta tags for updates on DX-458 

---

payments.yml

DX-533 Collect Fast Bug fixes

---

reports.yml

- Filter Improvements in Docs for Date & DateTime

DX-497 Transactions Reports EP Filters Improvements

---

README.md
data.yml

Improvement of Readme & 400 Errors on Connectors

DX-496 Improve 400 Error Responses on Connectors EP

---

data.yml

Include reference field in transaction endpoints

DX-546 Update data yml with transaction reference field

---

payments.yml

DX-559 Payments Linting

---

.github/workflows/pr-lint.yml
services.yml

DX-564 Lint Validation for Service with Redocly

---

data.yml

- Excluding Purses & Features
- Meta.fees.discounts added
- Meta.depositRates added
- Meta.lendingRates
- Meta.termDeposit
- Meta.CreditCard
- Meta.Loan
- Meta.Addresses
- Meta.Links

DX-569 Extension of Accounts EP with new CDR Fields

---

payments.yml

Removed Payment validation agreement

DX-571 Removing Payments Validation Agreement

---

core.yml

DX-610 Retrieve a business user - Extension

---

core.yml

- Adding additional Params for Creating a User

DX-586 Add Body Params for Business Consumer User

---

core.yml

DX-615 Fix for posted user Invalid

---

core.yml

Addition on Examples on the API Reference.

DX-620 Addition of Example of Business and non-business users

---

.github/workflows/CI-pipeline.yml

Deprecating Payments from API docs

DX-622 Deprecating Payments from API docs

---

reports.yml

DX-625 Schema Addition of Statements

---

reports.yml

DX-635 Update List Report types with Statement

---

.github/CODEOWNERS
core.yml

DX-638 Job Schema update

---

reports.yml

Improved Overall quality of the OpenAPI Spec

DX-625 Addition of 400 Errors on Statements EP

---

core.yml

DX-659 Retrieve an Event ID Endpoint

---

data.yml

and Sync API Hierarchy of Connectors Response

DX-667 Add example of cdrFAQ

---

.github/workflows/CI-pipeline.yml
README.md

🚀 **Deploy Prod**
This pull request automates the deployment of production-ready updates. 🛠️ It runs a series of checks and synchronisations across various API definitions to ensure consistency and reliability in your deployments. 🔄
🧰  **Changes in This PR:**
- Updates to API definitions for core, data, identity, reports, webhooks, enrich, affordability, and payments.
- Incorporates workflow checks for API consistency and integrity.
The New Structure is: 
- CORE
- DATA
- IDENTITY
- REPORTING (INSIGHTS)
- WEBHOOKS
- ENRICH
- AFFORDABILITY
- PAYMENT
[![Deploy Dev](https://github.com/basiqio/api-ref/actions/workflows/CI-dev-pipeline.yml/badge.svg)](https://github.com/basiqio/api-ref/actions/workflows/CI-dev-pipeline.yml) [![Deploy Prod](https://github.com/basiqio/api-ref/actions/workflows/CI- …

DX-673 Re-ordering API docs and updating CI Pipeline

---

data.yml

DX-680 Addition of Items on DepositRates & LendingRates

---

data.yml

DX-681 Rectification of Fees.discounts to array of objects

---

reports.yml

- Removed unused Report types from Report type Endpoint.

DX-696 Remove unused Report types

---

core.yml

Updating Retention period of Jobs and Events in our API.

DX-695 Retention period update

---

data.yml

DX-637 Addition of Pre-init Status in Connections EP

---

data.yml

This PR updates the definitions for ABN and ACN in our API Spec to improve accuracy and consistency.

DX-715 ABN and ACN Definitions

---

core.yml

🧰 **Changes**
- Removed Payment Events from Webhooks.

DX-735 Removed Payment Events

---

webhooks.yml

Removing Payment Reference from Webhooks.

DX-749 Removing Payment References

---

enrich.yml

- Adding Tags array in Enrich Endpoint.

DX-750 Add Tags on Enrich EP

---

reports.yml

🧰 Changes 
- Addition of `secureMonths` in `group.analysis.amount.secureMonths`
- Addition of `secureMonths` in `subgroup.analysis.amount.secureMonths`

DX-765 Addition of `secureMonths` in Groups and Subgroups

---

reports.yml

- Addition of Reports Title limit in Creating Reports.

DX-764 Reports title limit

---

reports.yml

- Addition of EXP-061 & EXP-062

DX-766 Add new groups for credit card repayment detections

---

core.yml

- Active example with Revoked & Expired.

DX-779 Addition of Active example

---

data.yml

The currency for the transaction amount.

DX-801 Adding `Currency` in Transactions EP

---

.github/CODEOWNERS
data.yml
enrich.yml

- Added Enrichment Tags Schema + examples.
- Added Transactions missing example.

DX-805 Data Enrichments Tags

---

core.yml

- GET events/types List event types
- GET /events/types/{id} Retrieve an event type

DX-804 Expose `connection.activated` event

---

reports.yml

DX-831 Fixed Reports API discrepancy

---

reports.yml

🧰 **Changes**
- Changed the description of the transaction `date` field from a simple date to a Zoned `DateTime` format as per API response.

DX-835 Fix: Update transaction date field to UTC DateTime

---

core.yml

**🧰 Changes Made**
- Added examples for job success, in-progress, and failed statuses in the OpenAPI spec.
- Removed Payments related Jobs.

DX-838 Job Status Updates

---

.github/workflows/pr-lint.yml

DX-777 API repo improvement

---

data.yml

This pull request enhances the Swagger documentation for the GET /transactions endpoint by clarifying the description of the next field.

DX-852 Refine Schema for `next` Field in GET /transactions Endpoint

---

.github/workflows/CI-pipeline.yml
reports.yml

DX-857 Removing Insights Label from Reports EP

---

data.yml

As it's optional in CDR Schema

DX-865 Added nullable in Addresses and Features

---

data.yml

DX-866 Fix String to Boolean

---

data.yml

- depositRates (Optional)
- fees (Optional)
- lendingRates (Optional)
- loan (Optional)
via CDR Schema: [Schema](https://consumerdatastandardsaustralia.github.io/standards/#cdr-banking-api_schemas_tocSbankingaccountdetailv3)

DX-868 Addition null objects

---

data.yml

- Fixed `loanCurrency`. 
- Removed `minInstalmentAmount`.

DX-870 Fixed Loan Schema

---

README.md

- Updated the deployment from api-ref to Basiq-docs 🔗.

DX-878 Migration from api-ref to Basiq-docs in Basiqio-oss
